opensearch_yum_repo_baseurl: "https://artifacts.opensearch.org/releases/bundle/opensearch/{{ opensearch_version.split('.')[0] }}.x/yum"
opensearch_yum_repo_gpgkey: "https://artifacts.opensearch.org/publickeys/opensearch-release.pgp"

opensearch_package: "opensearch-{{ opensearch_version }}"

opensearch_service_name: opensearch

opensearch_limit_nofile: 65536

opensearch_memory_high_mb: 2200

opensearch_user: opensearch
opensearch_group: opensearch

opensearch_home: /usr/share/opensearch
opensearch_plugin_bin: "{{ opensearch_home }}/bin/opensearch-plugin"
opensearch_config_dir: /etc/opensearch
opensearch_jvm_options_d: /etc/opensearch/jvm.options.d
opensearch_systemd_dropin_dir: "/etc/systemd/system/{{ opensearch_service_name }}.service.d"

opensearch_required_plugins:
  - opensearch-anomaly-detection
  - opensearch-alerting
  - opensearch-notifications
  - opensearch-notifications-core
  - opensearch-job-scheduler
  - opensearch-index-management
