all:
  vars:
    ansible_user: root

  children:

    alice_nodes:
      children:
        workers:
          vars:
            node_tier: worker
          hosts:
            alice-ingest-1:
              ansible_host: 203.0.113.11
              node_id: node-01
              epn_partition: 0
            alice-ingest-2:
              ansible_host: 203.0.113.12
              node_id: node-02
              epn_partition: 1
        storage:
          vars:
            node_tier: storage
          hosts:
            alice-ingest-3:
              ansible_host: 203.0.113.13
              node_id: node-03
              opensearch_heap_size: "1g"
            alice-ingest-4:
              ansible_host: 203.0.113.14
              node_id: node-04
            alice-ingest-5:
              ansible_host: 203.0.113.15
              node_id: node-05

    control:
      hosts:
        alice-ingest-3: {}

    background:
      hosts:
        alice-ingest-4:
          background_services: [rollup]
        alice-ingest-5:
          background_services: [digest]
