common_packages:
  - python3
  - python3-pip
  - tar
  - chrony
  - firewalld
  - ca-certificates

common_timezone: UTC

common_dnf_timeout: 600

common_vm_max_map_count: 262144
common_sysctl_conf_file: /etc/sysctl.d/99-opensearch.conf

common_swapfile_path: /swapfile
common_swapfile_size_mb: 2048
common_swappiness: 60


common_log_dirs:
  - "{{ log_root }}"
  - "{{ log_root }}/dds"
  - "{{ log_root }}/stdout"
