[supervisord]
nodaemon=true 

[program:dds]
command=python3 /app/producers/dds_producer.py
stdout_logfile=/dev/stdout    
stdout_logfile_maxbytes=0      
redirect_stderr=true
autorestart=true

[program:stdout]
command=python3 /app/producers/stdout_producer.py
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true
autorestart=true

[program:infologger]
command=python3 /app/producers/infologger_producer.py
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true
autorestart=true

[program:fluentbit]
command=/opt/fluent-bit/bin/fluent-bit -c /etc/fluent-bit/collector.yaml
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true
autorestart=true