[supervisord]
nodaemon=true

[program:fluentbit]
command=/opt/fluent-bit/bin/fluent-bit -c /etc/fluent-bit/collector.yaml
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true
autorestart=true
